apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-script
  labels:
    app: data-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-script
  template:
    metadata:
      labels:
        app: data-script
    spec:
      containers:
        - image: nazarveneta/quotes-data-script:v1
          name: data-script
          envFrom:
            - secretRef:
                name: data-script-secret
      initContainers:
        - image: nazarveneta/quotes-data-script:v1
          name: init-data-script
          args:
            [
              "sh",
              "-c",
              "until mysql -h ${MYSQL_DB_HOST} -u ${MYSQL_USER} -p${MYSQL_USER_PASSWORD} -e 'show databases;'; do echo waiting for mydb; sleep 2; done",
            ]
          envFrom:
            - secretRef:
                name: data-script-secret
      restartPolicy: Always
