apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  labels:
    app: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - image: nazarveneta/quotes-data:v1
          envFrom:
            - secretRef:
                name: data-secret
          name: db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              subPath: mysql
              name: volume-as7
      volumes:
        - name: volume-as7
          persistentVolumeClaim:
            claimName: claim-as7
      restartPolicy: Always
